/*6
This pipeline is used to sync git state to deployed state.
Any app.version file update will trigger this pipeline to sync state.
*/

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// CALCULATED VARIABLES
LABEL_NAME  = 'agent-' + new Date().getTime()
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

pipeline {
    agent {
        kubernetes {
            label "$LABEL_NAME"
            yaml '''
apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins-sa
  containers:
  - name: builder
    image: ChangeME # build base Dockerfile and push to dockerhub
    command: ['cat']
    tty: true
    volumeMounts:
    - name: dockersock
      mountPath: /var/run/docker.sock
  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
'''
        }
    }
    environment {
      GIT_SSH_COMMAND = "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
      TAG = "${env.BUILD_NUMBER}"
      registryCredential  = 'Docker' # Add your dockerhub creds 
    }
    stages {
      stage('GitClone') {
        steps {
          container('builder') {
            script {
              git url: 'GIT URL' # Add your assessment github link
            }
          }
        }
      }
      stage('Build') {
        steps {
          container('builder') {
            script {
              docker.withRegistry( '', registryCredential ) {
                sh '''
                  echo $TAG
                  cd devops-assessment/sample-service && docker build -t DOCKERHUB-REPO:sample-app-$TAG .
                  docker push DOCKERHUB-REPO:sample-app-$TAG
                '''
              }
            }
          }
        }
      }
      stage('Deploy') {
        steps {
          container('builder') {
            sh '''
			sudo kubectl create -f https://github.com/hiteshkumar685/Hitesh_devops_assesment/devops-assessment/devops-assessment/sample-service/k8s-manifest/app-service.yaml
            '''
          }
        }
      }
    }
}
